export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const STORE_LOGIN_DATA = 'STORE_LOGIN_DATA';
export const SAVE_SURVEY_EMAIL_DETAILS_FAIL = 'SAVE_SURVEY_EMAIL_DETAILS_FAIL';
export const SAVE_SURVEY_EMAIL_DETAILS_SUCCESS = 'SAVE_SURVEY_EMAIL_DETAILS_SUCCESS';
export const SAVE_SURVEY_EMAIL_DETAILS = 'SAVE_SURVEY_EMAIL_DETAILS';
